# Generated by Django 3.2.9 on 2022-02-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0003_alter_beast_tacticts'),
    ]

    operations = [
        migrations.AddField(
            model_name='beast',
            name='slug',
            field=models.SlugField(default=None, max_length=100, null=True, unique=True),
        ),
    ]
