# Generated by Django 3.2.9 on 2022-02-10 15:14

from django.db import migrations
from bestiary.models import Beast

def assing_slug(*args):
    for obj in Beast.objects.all():
        obj.save()

def assing_img(*arg):
    for obj in Beast.objects.all():
        obj.image.name = f'beasts/{obj.slug}.png'
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0007_beast_image'),
    ]

    operations = [
        migrations.RunPython(
            assing_slug,
            assing_img
        )
    ]
