# Generated by Django 3.2.9 on 2022-02-10 15:16

from django.db import migrations
from bestiary.models import Beast

def assing_img(*arg):
    for obj in Beast.objects.all():
        obj.image.name = f'beasts/{obj.slug}.png'
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0008_auto_20220210_1514'),
    ]

    operations = [
        migrations.RunPython(
            assing_img
        )
    ]
